name: '.NET code'
description: 'A Github action'
branding:
  icon: sliders
  color: purple
inputs:
  buildPath:
    description: 'buildPath'
    required: true
  folderName:
    description: 'folderName'
    required: true  
outputs:
  updated-dotnet:
    description: 'A boolean value'
  demo:
    description: 'A string value'        
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - '-buildPath'
  - ${{ inputs.buildPath }}
  - '-folderName'
  - ${{ inputs.folderName }}
  - '-filter'
  - ${{ inputs.filter }}
  - '-split'
  - ${{ inputs.split }}
