name: "test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'
  workflow_dispatch:    

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: get version
      id: version
      uses: ./
      with: 
        path: 'package.json'
        prop_path: 'version'
    - run: echo 'aaa'