name: '.NET code'

on:
  push:
    branches: [ main ]
    paths:

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Test
      id: set_var
      run: |
          content=`cat ./package.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=packageJson::$content"
      shell: bash

    - name: TestV2
      run: |
          echo "${{fromJson(steps.set_var.outputs.packageJson).version}}"
      shell: bash    

    - name: .NET code
      id: dotnet-code
      uses: os250082/ConsoleApp3@main
      env:
        GREETINGS: 'Hello, .NET developers!'
      with:
        buildPath: 'c:\LibsLocal'
        folderName: 'c:\LibsLocal'

    - name: 'Test Output'
      if: ${{ steps.dotnet-code.outputs.updated-dotnet }} == 'true'
      run: |
        echo 'Great Job ${{ steps.dotnet-code.outputs.demo }}'      