name: '.NET code'

on:
  push:
    branches: [ main ]
    paths:

  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running the workflow'
        required: true
        default: 'Manual run'   

jobs:
  Dotnet:
    runs-on: [self-hosted, ps_fat]
    steps:
    - uses: actions/checkout@v2

    - name: 'Print manual run reason'
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        echo 'Reason: ${{ github.event.inputs.reason }}'