name: '.NET code'

on:
  push:
    branches: [ main ]
    paths:

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Read Json File
      id: set_var
      run: |
          content=`cat ./inputs.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=inputsJson::$content"

    - name: .NET code
      id: dotnet-code
      uses: os250082/ConsoleApp3/TestsSplitter/TestsSplitter@main
      with:
        buildPath: ${{fromJson(steps.set_var.outputs.inputsJson).buildPath}}
        folderName: ${{fromJson(steps.set_var.outputs.inputsJson).folderName}}
        filter: ${{fromJson(steps.set_var.outputs.inputsJson).filter}}
        split: ${{fromJson(steps.set_var.outputs.inputsJson).split}}

    - name: 'Test Output'
      if: ${{ steps.dotnet-code.outputs.updated-dotnet }} == 'true'
      run: |
        echo 'Great Job ${{ steps.dotnet-code.outputs.demo }}'      