name: '.NET code'

on:
  push:
    branches: [ main ]
    paths:

  workflow_dispatch:  

jobs:
  Dotnet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: .NET code
      id: dotnet-code
      - servers: '[{"id": "serverId", "username": "username", "password": "password"}]'
      
      uses: os250082/ConsoleApp3/MyApp@main
      env:
        GREETINGS: 'Hello, .NET developers!'
      with:
        owner: $servers